"""Added optional filename

Revision ID: 3b7b10a32656
Revises: 1674b903b3ae
Create Date: 2025-05-07 14:45:31.458620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7b10a32656'
down_revision: Union[str, None] = '1674b903b3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'filename')
    # ### end Alembic commands ###
